networks:
  A1: {}
  B1: {}
  B2: {}
  C1: {}
  C2: {}
  C3: {}
  C4: {}
  D1: {}
  D2: {}
  E1: {}
  E2: {}
  E3: {}
  F1: {}
  F2: {}
  F3: {}
services:
  A-B1:
    image: nginx
    networks:
    - A1
    - B1
  A-B2:
    image: nginx
    networks:
    - A1
    - B2
  B1-C:
    image: nginx
    networks:
    - B1
    - C1
    - C2
  B2-C:
    image: nginx
    networks:
    - B2
    - C3
    - C3
  C-D1:
    image: nginx
    networks:
    - C1
    - C2
    - D1
  C-D2:
    image: nginx
    networks:
    - C3
    - C4
    - D2
  C2-C3:
    image: nginx
    networks:
    - C2
    - C3
  D1-E1:
    image: nginx
    networks:
    - D1
    - E1
  D2-E3:
    image: nginx
    networks:
    - D2
    - E3
  E1-E2:
    image: nginx
    networks:
    - E1
    - E2
  E1-F1:
    image: nginx
    networks:
    - E1
    - F1
  E2-E3:
    image: nginx
    networks:
    - E2
    - E3
  E2-F2:
    image: nginx
    networks:
    - E2
    - F2
  E3-F3:
    image: nginx
    networks:
    - E3
    - F3
  proxy:
    image: nginx
    networks:
    - A1
    ports:
    - '80'
  target:
    image: mysql
    networks:
    - F3
version: '3.8'
