networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
services:
  py1:
    image: python
    networks:
    - frontend
    tty: true
  py2:
    image: python
    networks:
    - frontend
    tty: true
  py3:
    image: python
    networks:
    - frontend
    tty: true
  py4:
    image: python
    networks:
    - frontend
    tty: true
  py5:
    image: python
    networks:
    - frontend
    tty: true
  tc:
    image: tomcat
    networks:
    - frontend
    ports:
    - '80'
version: '3.8'
