networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
services:
  py1:
    image: python
    networks:
    - frontend
  py10:
    image: python
    networks:
    - frontend
  py2:
    image: python
    networks:
    - frontend
  py3:
    image: python
    networks:
    - frontend
  py4:
    image: python
    networks:
    - frontend
  py5:
    image: python
    networks:
    - frontend
  py6:
    image: python
    networks:
    - frontend
  py7:
    image: python
    networks:
    - frontend
  py8:
    image: python
    networks:
    - frontend
  py9:
    image: python
    networks:
    - frontend
  tc:
    image: tomcat
    networks:
    - frontend
    ports:
    - '80'
version: '3.8'
