version: "3.8"

services:

  python:
    networks:
      - backend
      - db
    image: python

  tomcat:
    networks:
      - frontend
      - backend
    image: tomcat
    ports:
      - "3001:8080"

  mysql:
    # build: .
    networks:
      - db
    image: mysql

networks:
  frontend: {}
  backend: {}
  db: {}
