version: "3.8"

services:

  py:
    networks:
      - backend
      - frontend
    image: python

  tc:
    networks:
      - backend
      - frontend
    image: tomcat

  ms:
    # build: .
    networks:
      - backend
    image: mysql

  ng:
    networks:
      - frontend
    image: nginx
    ports:
      - "3001:8080"
networks:
  frontend: {}
  backend: {}
