version: "3.8"

services:

  py:
    networks:
      - backend
      - db
    image: python

  tc:
    networks:
      - frontend
      - backend
    image: tomcat
    ports:
      - "3001:8080"

  ms:
    # build: .
    networks:
      - db
    image: mysql

  ng:
    networks:
      - frontend
      - backend
    image: nginx
networks:
  frontend: {}
  backend: {}
  db: {}
