networks:
  A1: {}
  B1: {}
  B2: {}
  C1: {}
  C2: {}
  C3: {}
  C4: {}
  D1: {}
  D2: {}
  E1: {}
  E2: {}
  E3: {}
  F1: {}
  F2: {}
  F3: {}
services:
  A-B1:
    image: nginx
    networks:
    - A1
    - B1
  A-B2:
    image: nginx
    networks:
    - A1
    - B2
  B1-C:
    image: nginx
    networks:
    - B1
    - C1
    - C2
  B2-C:
    image: nginx
    networks:
    - B2
    - C3
    - C3
  C-D1:
    image: nginx
    networks:
    - C1
    - C2
    - D1
  C-D2:
    image: nginx
    networks:
    - C3
    - C4
    - D2
  C2-C3:
    image: nginx
    networks:
    - C2
    - C3
  D1-E1:
    image: nginx
    networks:
    - D1
    - E1
  D2-E3:
    image: nginx
    networks:
    - D2
    - E3
  E1-E2:
    image: nginx
    networks:
    - E1
    - E2
  E1-F1:
    image: nginx
    networks:
    - E1
    - F1
  E2-E3:
    image: nginx
    networks:
    - E2
    - E3
  E2-F2:
    image: nginx
    networks:
    - E2
    - F2
  E3-F3:
    image: nginx
    networks:
    - E3
    - F3
  atsea_app1:
    image: atsea_app
    networks:
    - A1
  atsea_app10:
    image: atsea_app
    networks:
    - D1
  atsea_app11:
    image: atsea_app
    networks:
    - E1
  atsea_app12:
    image: atsea_app
    networks:
    - E2
  atsea_app13:
    image: atsea_app
    networks:
    - E2
  atsea_app14:
    image: atsea_app
    networks:
    - E3
  atsea_app15:
    image: atsea_app
    networks:
    - F1
  atsea_app16:
    image: atsea_app
    networks:
    - F2
  atsea_app17:
    image: atsea_app
    networks:
    - F2
  atsea_app2:
    image: atsea_app
    networks:
    - A1
  atsea_app3:
    image: atsea_app
    networks:
    - B1
  atsea_app4:
    image: atsea_app
    networks:
    - C1
  atsea_app5:
    image: atsea_app
    networks:
    - C1
  atsea_app6:
    image: atsea_app
    networks:
    - C1
  atsea_app7:
    image: atsea_app
    networks:
    - C1
  atsea_app8:
    image: atsea_app
    networks:
    - C4
  atsea_app9:
    image: atsea_app
    networks:
    - C4
  atsea_db1:
    image: atsea_db
    networks:
    - A1
  atsea_db10:
    image: atsea_db
    networks:
    - F1
  atsea_db11:
    image: atsea_db
    networks:
    - F2
  atsea_db12:
    image: atsea_db
    networks:
    - F2
  atsea_db2:
    image: atsea_db
    networks:
    - B1
  atsea_db3:
    image: atsea_db
    networks:
    - B2
  atsea_db4:
    image: atsea_db
    networks:
    - B2
  atsea_db5:
    image: atsea_db
    networks:
    - C2
  atsea_db6:
    image: atsea_db
    networks:
    - C2
  atsea_db7:
    image: atsea_db
    networks:
    - D2
  atsea_db8:
    image: atsea_db
    networks:
    - E2
  atsea_db9:
    image: atsea_db
    networks:
    - F1
  mysql1:
    image: mysql
    networks:
    - B2
  mysql10:
    image: mysql
    networks:
    - F3
  mysql2:
    image: mysql
    networks:
    - C3
  mysql3:
    image: mysql
    networks:
    - D2
  mysql4:
    image: mysql
    networks:
    - D2
  mysql5:
    image: mysql
    networks:
    - E1
  mysql6:
    image: mysql
    networks:
    - E3
  mysql7:
    image: mysql
    networks:
    - F1
  mysql8:
    image: mysql
    networks:
    - F3
  mysql9:
    image: mysql
    networks:
    - F3
  proxy:
    image: nginx
    networks:
    - A1
    ports:
    - '80'
  python1:
    image: python
    networks:
    - A1
  python2:
    image: python
    networks:
    - B1
  python3:
    image: python
    networks:
    - B2
  python4:
    image: python
    networks:
    - C2
  python5:
    image: python
    networks:
    - C3
  python6:
    image: python
    networks:
    - C3
  python7:
    image: python
    networks:
    - D1
  python8:
    image: python
    networks:
    - E1
  python9:
    image: python
    networks:
    - E3
  target:
    image: mysql
    networks:
    - B2
  tomcat1:
    image: tomcat
    networks:
    - B1
  tomcat10:
    image: tomcat
    networks:
    - E2
  tomcat11:
    image: tomcat
    networks:
    - E3
  tomcat12:
    image: tomcat
    networks:
    - F3
  tomcat2:
    image: tomcat
    networks:
    - C2
  tomcat3:
    image: tomcat
    networks:
    - C3
  tomcat4:
    image: tomcat
    networks:
    - C4
  tomcat5:
    image: tomcat
    networks:
    - C4
  tomcat6:
    image: tomcat
    networks:
    - D1
  tomcat7:
    image: tomcat
    networks:
    - D1
  tomcat8:
    image: tomcat
    networks:
    - D2
  tomcat9:
    image: tomcat
    networks:
    - E1
version: '3.8'
